file(MAKE_DIRECTORY "${TMP}")
set(count 0)
function(run_case name expected out_pattern err_pattern)
  execute_process(COMMAND "${PROGRAM}" ${ARGN} WORKING_DIRECTORY "${TMP}"
    RESULT_VARIABLE code OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 3)
  if(NOT "${code}" STREQUAL "${expected}")
    message(FATAL_ERROR "${name}: 退出码 ${code}，预期 ${expected}")
  endif()
  if(out_pattern STREQUAL "EMPTY")
    if(NOT out STREQUAL "")
      message(FATAL_ERROR "${name}: stdout 应为空")
    endif()
  elseif(NOT out MATCHES "${out_pattern}")
    message(FATAL_ERROR "${name}: stdout 不匹配")
  endif()
  if(err_pattern STREQUAL "EMPTY")
    if(NOT err STREQUAL "")
      message(FATAL_ERROR "${name}: stderr 应为空")
    endif()
  elseif(NOT err MATCHES "${err_pattern}")
    message(FATAL_ERROR "${name}: stderr 不匹配")
  endif()
  math(EXPR next "${count} + 1")
  set(count ${next} PARENT_SCOPE)
endfunction()
set(valid "listen=0.0.0.0:8080\nbackend=127.0.0.1:9001\n")
file(WRITE "${TMP}/valid config.conf" "${valid}")
file(WRITE "${TMP}/bad.conf" "listen=127.0.0.1:0\nbackend=127.0.0.1:2\n")
file(SHA256 "${SOURCE}/configs/example.conf" example_before)
file(SHA256 "${TMP}/valid config.conf" valid_before)
file(SHA256 "${TMP}/bad.conf" bad_before)
run_case(help 0 "TCP 代理：固定轮询.*UDP 按 flow 固定后端，尽力转发.*TCP/UDP 均可运行" EMPTY --help)
run_case(example 0 "^配置有效：TCP，后端数量=2\n$" EMPTY --check-config "${SOURCE}/configs/example.conf")
run_case(spaces_relative 0 "^配置有效：TCP，后端数量=1\n$" EMPTY --check-config "valid config.conf")
run_case(no_args 2 EMPTY "用法错误.*--help")
run_case(unknown 2 EMPTY "用法错误.*--help" --unknown)
run_case(missing_path 2 EMPTY "用法错误.*--help" --check-config)
run_case(duplicate 2 EMPTY "用法错误.*--help" --check-config x --check-config x)
run_case(extra 2 EMPTY "用法错误.*--help" --check-config x y)
run_case(help_extra 2 EMPTY "用法错误.*--help" --help x)
run_case(help_mixed 2 EMPTY "用法错误.*--help" --help --check-config x)
run_case(help_as_path 2 EMPTY "用法错误.*--help" --check-config --help)
run_case(duplicate_help 2 EMPTY "用法错误.*--help" --help --help)
run_case(duplicate_check 2 EMPTY "用法错误.*--help" --check-config --check-config)
run_case(bad 1 EMPTY "第 1 行.*无效" --check-config bad.conf)
run_case(missing_file 1 EMPTY "文件 missing.conf" --check-config missing.conf)
run_case(directory 1 EMPTY "文件.*必须为普通文件" --check-config "${TMP}")
run_case(device 1 EMPTY "文件 /dev/null.*必须为普通文件" --check-config /dev/null)
execute_process(COMMAND mkfifo "${TMP}/pipe" RESULT_VARIABLE fifo_rc ERROR_QUIET)
if(NOT fifo_rc EQUAL 0 AND NOT EXISTS "${TMP}/pipe")
  message(FATAL_ERROR "FIFO fixture 创建失败")
endif()
run_case(fifo 1 EMPTY "文件.*必须为普通文件" --check-config "${TMP}/pipe")
file(CREATE_LINK "${TMP}/valid config.conf" "${TMP}/link.conf" SYMBOLIC RESULT link_rc)
if(NOT link_rc STREQUAL "0")
  message(FATAL_ERROR "symlink fixture 创建失败: ${link_rc}")
endif()
run_case(symlink 0 "^配置有效：TCP，后端数量=1\n$" EMPTY --check-config link.conf)
file(WRITE "${TMP}/unreadable.conf" "${valid}")
file(CHMOD "${TMP}/unreadable.conf" PERMISSIONS OWNER_WRITE)
execute_process(COMMAND id -u OUTPUT_VARIABLE uid OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE id_rc)
if(NOT id_rc EQUAL 0)
  message(FATAL_ERROR "无法确定普通用户权限测试条件")
endif()
if(uid STREQUAL "0")
  message(STATUS "权限测试未验证：root 可绕过读取权限")
else()
  run_case(permission 1 EMPTY "文件.*unreadable.conf" --check-config unreadable.conf)
endif()
execute_process(COMMAND chmod 600 "${TMP}/unreadable.conf" RESULT_VARIABLE restore_rc)
if(NOT restore_rc EQUAL 0)
  message(FATAL_ERROR "权限 fixture 恢复失败")
endif()
string(LENGTH "${valid}" size)
math(EXPR padding "65536 - ${size} - 1")
string(REPEAT x ${padding} payload)
file(WRITE "${TMP}/limit.conf" "${valid}#${payload}")
run_case(limit 0 "^配置有效：TCP，后端数量=1\n$" EMPTY --check-config limit.conf)
file(APPEND "${TMP}/limit.conf" x)
run_case(over_limit 1 EMPTY "文件.*limit.conf.*65536" --check-config limit.conf)
file(SHA256 "${SOURCE}/configs/example.conf" example_after)
file(SHA256 "${TMP}/valid config.conf" valid_after)
file(SHA256 "${TMP}/bad.conf" bad_after)
if(NOT example_before STREQUAL example_after OR NOT valid_before STREQUAL valid_after OR NOT bad_before STREQUAL bad_after)
  message(FATAL_ERROR "配置被改写")
endif()
message(STATUS "CLI 用例数=${count}，配置 SHA256 前后相同")

file(WRITE "${TMP}/udp.conf" "protocol=udp\nscheduler=round_robin\n${valid}")
run_case(udp_check 0 "^配置有效：UDP，后端数量=1\n$" EMPTY --check-config udp.conf)
file(WRITE "${TMP}/tcp.conf" "scheduler=round_robin\nprotocol=tcp\n${valid}")
run_case(tcp_explicit 0 "^配置有效：TCP，后端数量=1\n$" EMPTY --check-config tcp.conf)
message(STATUS "扩展后 CLI 用例数=${count}")
foreach(protocol tcp udp)
  foreach(health off tcp_connect)
    file(WRITE "${TMP}/health.conf" "protocol=${protocol}\nhealth_check=${health}\n${valid}")
    string(TOUPPER "${protocol}" label)
    run_case(health_check 0 "^配置有效：${label}，后端数量=1\n$" EMPTY --check-config health.conf)
  endforeach()
endforeach()
run_case(health_help 0 "health_check 默认 off.*UDP 仅在启用 health_check=tcp_connect 时需在相同 IP/端口" EMPTY --help)
message(STATUS "最终 CLI 用例数=${count}（含 health_check）")
foreach(protocol tcp udp)
  foreach(health off tcp_connect)
    foreach(metrics off stderr)
      file(WRITE "${TMP}/metrics.conf" "protocol=${protocol}\nhealth_check=${health}\nmetrics=${metrics}\n${valid}")
      string(TOUPPER "${protocol}" label)
      run_case(metrics_check 0 "^配置有效：${label}，后端数量=1\n$" EMPTY --check-config metrics.conf)
    endforeach()
  endforeach()
endforeach()
run_case(metrics_help 0 "metrics 默认 off.*同步 stderr 可能阻塞业务" EMPTY --help)
message(STATUS "最终 CLI 用例数=${count}（含 metrics）")

# V1.0/S1: protect the clarified contract without freezing OS strerror text.
run_case(ready_help 0 "ready 仅表示监听就绪，不保证后端可达或 Healthy" EMPTY --help)
run_case(stop_help 0 "固定 1 秒内排空用户态 pending，不保证送达.*UDP 停止关闭 flows，不保证排空.*同步输出阻塞时不保证进程按时退出。\n$" EMPTY --help)
file(WRITE "${TMP}/first-error.conf" "listen=127.0.0.1:80\nsecret_unknown=DO_NOT_ECHO\nbackend=bad\n")
run_case(first_error 1 EMPTY "^配置错误：第 2 行：[^\n]+\n$" --check-config first-error.conf)
execute_process(COMMAND "${PROGRAM}" --check-config "${TMP}/first-error.conf"
  OUTPUT_VARIABLE out ERROR_VARIABLE err RESULT_VARIABLE code TIMEOUT 3)
if(err MATCHES "DO_NOT_ECHO|secret_unknown")
  message(FATAL_ERROR "诊断回显了配置内容")
endif()
file(WRITE "${TMP}/eof.conf" "listen=127.0.0.1:80\n")
run_case(eof 1 EMPTY "^配置错误：EOF（第 2 行）：[^\n]+\n$" --check-config eof.conf)
file(WRITE "${TMP}/duplicate.conf" "${valid}metrics=off\nmetrics=off\n")
run_case(duplicate_same 1 EMPTY "^配置错误：第 4 行：[^\n]+\n$" --check-config duplicate.conf)
file(GLOB old_examples RELATIVE "${SOURCE}/configs" "${SOURCE}/configs/*.conf")
foreach(example IN LISTS old_examples)
  if(EXISTS "${SOURCE}/configs/${example}")
    file(SHA256 "${SOURCE}/configs/${example}" before)
    run_case(old_example 0 "^配置有效：(TCP|UDP)，后端数量=[0-9]+\n$" EMPTY --check-config "${SOURCE}/configs/${example}")
    file(SHA256 "${SOURCE}/configs/${example}" after)
    if(NOT before STREQUAL after)
      message(FATAL_ERROR "旧示例被改写")
    endif()
  endif()
endforeach()
file(REMOVE "${TMP}/pipe" "${TMP}/link.conf")
message(STATUS "V1.0 CLI 用例数=${count}；FIFO/link 已清理")
